// import { Product } from './interfaces/Product';

// export const products: Product[] = [
//   {
//     id: 1,
//     image: '/images/item9.jpg',
//     title: 'Grey hoodie1',
//     price: '$181.00',
//     type: 'Dog',
//     category: 'Food',
//   },
//   {
//     id: 2,
//     image: '/images/item10.jpg',
//     title: 'Hoodie1',
//     price: '$381.00',
//     type: 'Dog',
//     category: 'Food',
//   },
//   {
//     id: 3,
//     image: '/images/item11.jpg',
//     title: 'Grey1',
//     price: '$281.00',
//     type: 'Dog',
//     category: 'Food',
//   },
//   {
//     id: 4,
//     image: '/images/item12.jpg',
//     title: 'Hoodie Grey',
//     price: '$151.00',
//     type: 'Dog',
//     category: 'Food',
//   },
//   {
//     id: 5,
//     image: '/images/item13.jpg',
//     title: 'Grey hoodie',
//     price: '$181.00',
//     type: 'Dog',
//     category: 'Food',
//   },
//   {
//     id: 6,
//     image: '/images/item14.jpg',
//     title: 'Hoodie',
//     price: '$38.00',
//     type: 'Bird',
//     category: 'Food',
//   },
//   {
//     id: 7,
//     image: '/images/item15.jpg',
//     title: 'Grey',
//     price: '$28.00',
//     type: 'Cat',
//     category: 'Food',
//   },
//   {
//     id: 8,
//     image: '/images/item16.jpg',
//     title: 'Hoodie Grey',
//     price: '$15.00',
//     type: 'Bird',
//     category: 'Food',
//   },
//   //  Clothing
//   {
//     id: 9,
//     image: '/images/item1.jpg',
//     title: 'Grey hoodie hoodie',
//     price: '$18.00',
//     type: 'T-shirt',
//     category: 'Clothing',
//   },
//   {
//     id: 10,
//     image: '/images/item2.jpg',
//     title: 'Hoodie',
//     price: '$38.00',
//     type: 'T-shirt',
//     category: 'Clothing',
//   },
//   {
//     id: 11,
//     image: '/images/item3.jpg',
//     title: 'Grey',
//     price: '$28.00',
//     type: 'T-shirt',
//     category: 'Clothing',
//   },
//   {
//     id: 12,
//     image: '/images/item4.jpg',
//     title: 'Hoodie Grey',
//     price: '$15.00',
//     type: 'T-shirt',
//     category: 'Clothing',
//   },
// ];
